name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install OpenCV Development Libraries & Ninja
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev ninja-build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -G Ninja

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build --output-on-failure
